### PR TITLE
feat(apps:update): add ability to use ZENDESK_APP_ID env var during apps:update

### PR DESCRIPTION
**Pull request by yoshdog**
## Description

Someones we want to have seperate apps for staging and production. In these cases they will have a seperate app_id.

In this change we will allow users to set the `ZENDESK_APP_ID` environment variable to specify which app_id to use. This will allow developers to set this in their CICD pipelines.

  

### [`bb2f886`](https://github.com/zendesk/zcli/pull/254/commits/bb2f886b5e09778a094f559fb2e2bbe3949a7a98) feat: add ability to use ZENDESK_APP_ID env var during apps:update

Someones we want to have seperate apps for staging and production. In these cases they will have a seperate app_id.

In this change we will allow users to set the `ZENDESK_APP_ID` environment variable to specify which app_id to use. This will allow developers to set this in their CICD pipelines.

Fixes: https://github.com/zendesk/zcli/issues/173

## Detail

closes: https://github.com/zendesk/zcli/issues/173

## Checklist

- [x] :guardsman: includes new unit and functional tests

### CODE REVIEW

**Review by anushkafka — COMMENTED** [review]
This is looking good 👍 Just need to fix the type errors and update tests.

**Comment by yoshdog** [comment]
updated @anushkafka 
can you please have a review again?

**Comment by anushkafka** [comment]
@yoshdog Thanks for the update, this is looking good. Have u been able to verify your use case? I can do a highlevel QA from my side to verify nothing is breaking 👍

**Review by anushkafka — APPROVED** [review]

**Comment by yoshdog** [comment]
all good on my side @anushkafka

**Review by zFlabmonsta — APPROVED** [review]

**Comment by anushkafka** [comment]
General QA Approved ✅ 

Screenshot 2024-09-02 at 11 29 31 PM

Screenshot 2024-09-02 at 11 34 49 PM

**Pull request merged**
